name: Deploy Posthog LLM to Caprover

on:
    push:
        branches: ['llm-main']

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set IMAGE URL
              id: set-vars
              run: |
                  echo "IMAGE_URL=postlang/posthog-llm:${{ github.sha }}" >> $GITHUB_ENV
                  echo "LATEST_TAG=postlang/posthog-llm:latest" >> $GITHUB_ENV

            - name: Build and push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ${{ env.IMAGE_URL }}
                      ${{ env.LATEST_TAG }}
